version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: kkun-quiz-app/frontend:latest
    depends_on:
      - backend
    # Nếu để FE tự serve qua nginx bên trong image FE thì expose trực tiếp 80,
    # còn nếu dùng nginx chung, thay thế `frontend` bằng volume static.
    networks:
      - web

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: yourrepo/backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # ví dụ cấu hình DB:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
      SERVER_FORWARD_HEADERS_STRATEGY: native
    depends_on:
      - db
    networks:
      - web

  # Nginx proxy/serve FE (tuỳ chọn nhưng gọn nhất)
  nginx:
    image: nginx:alpine
    volumes:
      # lấy build FE từ container frontend (hoặc build ra volume/artifact rồi mount)
      - frontend-static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - web

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - web

volumes:
  dbdata:
  frontend-static:

networks:
  web:
    driver: bridge
