services:
  backend:
    image: ghcr.io/thaihoandev/kkun-quiz-app-backend:latest
    env_file:
      - ./backend.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    image: ghcr.io/thaihoandev/kkun-quiz-app-frontend:latest
    # Thường FE (Nginx serve static) không dùng env_file lúc runtime
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

  # mcq:
  #   image: ghcr.io/thaihoandev/kkun-quiz-app-mcq:latest
  #   # Nếu mcq cần biến môi trường thì bật dòng dưới:
  #   # env_file:
  #   #   - ./mcq.env
  #   depends_on:
  #     - backend
  #   networks:
  #     - appnet

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kkunquizapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
