name: Build & Push Images (Docker Hub)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'QuizAppBackend/**'
      - 'my-frontend/**'
      - 'mcq_extraction/**'
      - '.github/workflows/build-and-push-dockerhub.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'QuizAppBackend/**'
      - 'my-frontend/**'
      - 'mcq_extraction/**'
  tags:
    - 'v*'  # optional: khi tạo tag v1.2.3 sẽ retag

permissions:
  contents: read

env:
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USER }}/kkun-quiz-app

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./QuizAppBackend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-backend:latest
            ${{ env.IMAGE_PREFIX }}-backend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  frontend:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./my-frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-frontend:latest
            ${{ env.IMAGE_PREFIX }}-frontend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  mcq_extraction:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build & Push MCQ Extraction
        uses: docker/build-push-action@v6
        with:
          context: ./mcq_extraction
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-mcq:latest
            ${{ env.IMAGE_PREFIX }}-mcq:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # optional: gắn tag version khi bạn tạo release tag v*
  retag-on-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [backend, frontend, mcq_extraction]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag latest -> version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          for svc in backend frontend mcq; do
            src="${{ env.IMAGE_PREFIX }}-$svc:latest"
            dst="${{ env.IMAGE_PREFIX }}-$svc:${VERSION}"
            docker pull "$src"
            docker tag "$src" "$dst"
            docker push "$dst"
          done
