package com.kkunquizapp.QuizAppBackend.chatBot.service;

import com.kkunquizapp.QuizAppBackend.chatBot.dto.TopicGenerateRequest;
import com.kkunquizapp.QuizAppBackend.question.dto.QuestionResponseDTO;

import java.util.List;

public interface GeminiService {

    /**
     * Generate question list based on topic + type + constraints
     *
     * @param request TopicGenerateRequest contains:
     *                - topic
     *                - count
     *                - language
     *                - questionType
     *                - quizId (for deduplication)
     *                - timeLimit
     *                - points
     *                - dedupe
     * @return List<QuestionResponseDTO> generated by Gemini
     */
    List<QuestionResponseDTO> generateByTopic(TopicGenerateRequest request);
}
